pr3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'pr3.views.home', name='home'),
    # url(r'^login/$', 'pr3.views.supplierlogin', name='login'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^blog/', include('blog.urls')),
    url(r'^subscriber/', include('subscriber.urls')),
    url(r'^supplier/', include('supplier.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

supplier/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:


    url(r'^profile/$', 'supplier.views.supplier_profile', name='supplier-profile'),
    url(r'^profile/api/(?P<id>\d+)/$', 'supplier.views.supplier_profile_json', name='supplier-profile-json'),
    url(r'^profile/info/$', 'supplier.views.supplier_profile', name='supplier-profile'),
    
    url(r'^profile/company/info/$', 'supplier.views.comapny_info', name='comapny-info'),
    url(r'^profile/company/info/api/(?P<supplier_id>\d+)/$', 'supplier.views.comapny_info_json', name='comapny-info-json'),
    
    url(r'^profile/company/revenue/$', 'supplier.views.company_revenue', name='company-revenue'),
    url(r'^profile/company/revenue/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_revenue_json', name='company-revenue-json'),

    url(r'^profile/company/contacts/$', 'supplier.views.company_contacts', name='company-contacts'),
    
    url(r'^profile/company/contacts/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_contacts_json', name='company-contacts-json'),
    url(r'^profile/company/references/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_references_json', name='company-ref-json'),

    url(r'^profile/company/licenses/$', 'supplier.views.company_licenses', name='company-licenses'),
    url(r'^profile/company/licenses/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_licenses_json', name='company-licenses-json'),
    url(r'^profile/company/cert/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_cert_json', name='company-cert-json'),
    
    url(r'^profile/company/products-services/$', 'supplier.views.company_products_services', name='company-products-services'),
    url(r'^profile/company/products-services/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_products_services_json',
                                                                    name='company-product-services-json'),
    url(r'^profile/company/certification/$', 'supplier.views.company_certification', name='company-certification'),
    url(r'^profile/company/certification/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_certification_json',
                                                                    name='company-certification-json'),


    url(r'^search-corporation/$', 'supplier.views.search_corporation', name='search-corporation'),
    url(r'^search_buyers/$', 'supplier.views.search_buyers', name='search-buyers'),
    url(r'^save_buyers/$', 'supplier.views.save_buyers', name='save-buyers'),
    url(r'^delete_buyer/$', 'supplier.views.delete_buyer', name='delete-buyers'),
    url(r'^add_manual_buyer/$', 'supplier.views.add_manual_buyer', name='add-manual-buyers'),

    url(r'^search/buyer/$', 'supplier.views.search_buyer', name='search-buyer'),
    url(r'^submission-status/$', 'supplier.views.supplier_submission_status', name='submission-status'),
    url(r'^/profile/capability-statement//$', 'supplier.views.supplier_capability_statement'),

    url(r'^product-service/code/(?P<code_type>\w+)/search/$', 'supplier.views.search_code', name='search-code'),
    url(r'^search/code/(?P<code_type>\w+)/$', 'supplier.views.search', name='search'),
    
)

supplier/models.py
from django.db import models
from django.contrib.auth.models import User
from supplier.choices import *
from decimal import Decimal
# Create your models here.
class ProductAndServiceCategory(models.Model):
    '''
    Product category 
    '''
    category_name = models.CharField(max_length=256, blank=True, null=True, verbose_name='Category Name')

    def __unicode__(self):
        return self.category_name

class ProductServiceCode(models.Model):
    '''
    This model will take SIC, NAICS etc code.
    code_type = SERVICE_CODE_TYPE
    '''
    code = models.CharField(max_length=50, blank=True, null=True, verbose_name='Code', unique=True)
    code_type = models.CharField(max_length=15, choices=SERVICE_CODE_TYPE, blank=True, null=True, verbose_name='Code Type')
    title = models.CharField(max_length=50, blank=True, null=True, verbose_name='Title')
    common_keywords = models.CharField(max_length=200, blank=True, null=True, verbose_name='Common Keywords')
    category = models.ForeignKey(ProductAndServiceCategory, blank=True, null=True)

    def __unicode__(self):
        return "%s: %s" % (self.code_type, self.code)


class Buyer(models.Model):
    company_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Company Name')
    login_url = models.URLField(max_length=256, blank=True, null=True, verbose_name='Login Url')
    registration_url = models.URLField(max_length=256, blank=True, null=True, verbose_name='Registration Url')
    buyer_introduction = models.CharField(max_length=500, blank=True, null=True, verbose_name='Buyer Introduction')
    state = models.CharField(max_length=100, blank=True, null=True, verbose_name='State')
    ps_buy_code = models.ManyToManyField(ProductServiceCode, blank=True, related_name='comp_buy_codes')
    product_service_category = models.ManyToManyField(ProductAndServiceCategory, blank=True)

    def __unicode__(self):
        return self.company_name

class Supplier(models.Model):
    user = models.OneToOneField(User)
    salutation = models.CharField(max_length=5, blank=True, null=True, verbose_name='Salutation')
    first_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='First Name')
    last_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Last Name')
    position = models.CharField(max_length=50, blank=True, null=True, verbose_name='Position')
    phone_number = models.CharField(max_length=25, blank=True, null=True, verbose_name='Phone Number')
    fax_number = models.CharField(max_length=25, blank=True, null=True, verbose_name='Fax Number')
    cell_number = models.CharField(max_length=25, blank=True, null=True, verbose_name='Cell Number')
    contact_email = models.EmailField(blank=True,null=True, verbose_name='Contact E-Mail')
    contact_address = models.CharField(max_length=500, blank=True,null=True, verbose_name='Contact Address')
    country = models.CharField(max_length=50, blank=True, null=True, verbose_name='Country')
    state = models.CharField(max_length=50, blank=True, null=True, verbose_name='State')
    city = models.CharField(max_length=50, blank=True, null=True, verbose_name='City')
    zip_code = models.CharField(max_length=15, blank=True, null=True, verbose_name='Zip Code')
    method_of_notification = models.CharField(max_length=10, blank=True, null=True, verbose_name='Method of Notification')
    preferred_password = models.CharField(max_length=128, blank=True, null=True, verbose_name='Password')
    subscription_status = models.CharField(max_length=10, blank=True, null=True, verbose_name='Subscription Status')
    subscription_date = models.DateField(blank=True, null=True)
    subscription_expire_date = models.DateField(blank=True, null=True)
    profile_completion_status = models.CharField(max_length=10, blank=True, null=True, verbose_name='Profile Completion Status') 

    def __unicode__(self):
        return str(self.id)

    def get_profile_completion_status_redirect_url(self):
        if self.profile_completion_status == None:
            redirect_url = "/supplier/profile/info/"
        elif int(self.profile_completion_status) == 1:
            redirect_url = "/supplier/profile/company/revenue/"
        elif int(self.profile_completion_status) == 2:
            redirect_url = "/supplier/profile/company/contacts/"
        elif int(self.profile_completion_status) == 3:
            redirect_url = "/supplier/profile/company/licenses/"
        elif int(self.profile_completion_status) == 4:
            redirect_url = "/supplier/profile/company/products-services/"
        elif int(self.profile_completion_status) == 5:
            redirect_url = "/supplier/profile/company/certification/"
        elif int(self.profile_completion_status) == 6:
            redirect_url = "/supplier/submission-status/"
        elif int(self.profile_completion_status) == 0:
            redirect_url = "/supplier/profile/company/info/"
        elif int(self.profile_completion_status) == -1:
            redirect_url = "/supplier/profile/info/"
        else:
            redirect_url = "/supplier/submission-status/"

        return redirect_url

    def is_profile_complete(self):
        if self.salutation == None or self.salutation == '':
            return False
        elif self.first_name == None or self.first_name == '':
            return False
        elif self.last_name == None or self.last_name == '':
            return False
        elif self.position == None or self.position == '':
            return False
        elif self.phone_number == None or self.phone_number == '':
            return False
        elif self.cell_number == None or self.cell_number == '':
            return False
        elif self.contact_email == None or self.contact_email == '':
            return False
        elif self.contact_address == None or self.contact_address == '':
            return False
        elif self.country == None or self.country == '':
            return False
        elif self.state == None or self.state == '':
            return False
        elif self.city == None or self.city == '':
            return False
        elif self.preferred_password == None or self.preferred_password == '':
            return False
        else:
            return True


    def get_full_name(self):
        name = self.salutation
        if self.first_name:
            name += " " + self.first_name
        if self.last_name:
            name += " " + self.last_name
        return name

class CompanyCapabilityStatement(models.Model):
    capability_statement = models.TextField(max_length=250, blank=True, null=True, verbose_name='Capability Statement')
    upload_doc = models.FileField(blank=True, null=True, verbose_name='Document Upload',
        upload_to='attachment/doc')
    upload_video = models.CharField(max_length=250, blank=True, null=True)

    def __unicode__(self):
        return "%s" % (self.capability_statement[:20])
   

class Address(models.Model):
    address_title = models.CharField(max_length=200, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    zip_code = models.CharField(max_length=50, blank=True, null=True)
    address_type = models.CharField(max_length=5, blank=True, null=True)

    def __unicode__(self):
        return "%s->%s" % (self.country, self.city)


class SupplierCompany(models.Model):
    supplier = models.OneToOneField(Supplier)
    comp_name = models.CharField(max_length=200, blank=True, null=True, verbose_name='Legal Company Name')
    organization_type = models.CharField(max_length=50, blank=True, null=True, verbose_name='Organization Type')
    doing_business_as = models.CharField(max_length=200, blank=True, null=True, verbose_name='DBA Company Name')
    tax_id_number = models.CharField(max_length=50, blank=True, null=True, verbose_name='Federal Tax ID')
    social_security_number = models.CharField(max_length=50, blank=True, null=True, verbose_name='Social Security Number')
    comp_dunn_street = models.CharField(max_length=50, blank=True, null=True, verbose_name='Dunn & Brad Street Number')
    comp_phone = models.CharField(max_length=20, blank=True, null=True, verbose_name='Company Phone Number')
    comp_fax = models.CharField(max_length=20, blank=True,null=True, verbose_name='Company Fax Number')
    comp_url = models.CharField(max_length=100, blank=True,null=True, verbose_name='Company Website (URL)')
    corporate_email = models.EmailField(blank=True,null=True, verbose_name='Corporate E-Mail')
    year_established = models.DateField(max_length=15,null=True, blank=True, verbose_name='Year Business was Established')
    num_of_employees = models.CharField(max_length=10,null=True, blank=True, verbose_name='Number Of Employees')
    # country = models.CharField(max_length=96, blank=True, null=True, verbose_name='Country')
    # state = models.CharField(max_length=96, blank=True, null=True, verbose_name='State')
    capability = models.ForeignKey(CompanyCapabilityStatement, blank=True, null=True)
    ps_categories = models.ManyToManyField(ProductAndServiceCategory, blank=True)
    product_service_description = models.TextField(max_length=200, blank=True,null=True, verbose_name='Product & Service Description')
    comp_logo = models.ImageField(blank=True, null=True, verbose_name='Current Company Logo', 
        upload_to='attachment/company/')
    comp_picture = models.ImageField(blank=True, null=True, verbose_name='Current Company/Personal Picture',
        upload_to='attachment/company/')
    comp_address = models.ForeignKey(Address, blank=True, null=True)

    def __unicode__(self):
        return str(self.id)
    


class Revenue(models.Model):
    company = models.OneToOneField(SupplierCompany)

supplier/forms.py
from django import forms
from supplier.models import *

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Supplier
        exclude = ['subscription_status', 'profile_completion_status']


class CompInfoForm(forms.ModelForm):
    class Meta:
        model = SupplierCompany
        exclude = ['']


class CapabilityForm(forms.ModelForm):
    class Meta:
        model = CompanyCapabilityStatement
        exclude = ['']


class RevenueForm(forms.ModelForm):
    class Meta:
        model = Revenue
        exclude = ['company',]

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['']

class CompanyLicenseForm(forms.ModelForm):
    class Meta:
        model = CompanyLicense
        exclude = ['company',]

class BusinessCertificateForm(forms.ModelForm):
    class Meta:
        model = BusinessCertificate
        exclude = ['company',]
    # def save(self, commit=False):
    #   license = super(CompanyLicenseForm, self).save(commit=False)

class CompanyContactForm(forms.ModelForm):
    class Meta:
        model = CompanyContact
        exclude = ['company',]

class CompanyReferenceForm(forms.ModelForm):
    class Meta:
        model = Reference
        exclude = ['company',]

class CompanyCertificationForm(forms.ModelForm):
    class Meta:
        model = CompanyCertification
        exclude = ['company',]

class CertificateNameForm(forms.ModelForm):
    class Meta:
        model = CertificateName
        exclude = ['display_order','active']

class CompanyProductServiceForm(forms.ModelForm):

    def clean_naics_code(self):
        data = self.cleaned_data['naics_code']
        if data != '':
            return data
        else:
            return data

    def save(self):
        code = super(CompanyProductServiceForm, self).save(commit=False)
        code.save()
        return code
        
    class Meta:
        model = CompanyProductService
        exclude = ['company',]

templates/supplier/comapny_info.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/form/company_info_form.html" %}	
{% endblock %}

{% block page_js %}
<script type="text/javascript">
$('#pre-selected-options').multiSelect({
    selectableHeader: "<div class='bg-danger'>Selectable Category</div>",
    selectionHeader: "<div class='bg-danger'>Selected Category</div>"
});


pr.controller('CompInfoController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company profile controller...");
        var sup_id = $("#id_supplier").val();
        var url = "/supplier/profile/company/info/api/"+sup_id+"/"
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                console.log(data);
                $scope.comp = data;
                $scope.capability = data.capability
                
        }).error(function() {
            console.log("no company info")
        });
    }
    $scope.init();

}]);

</script>
{% endblock %}

templates/supplier/comp_cert_form.html
<table class="table certificate" ng-controller="CompCertController">
<form method="post" action="/supplier/profile/company/certification/" enctype="multipart/form-data">{% csrf_token %}
<input type="hidden" name="supplier" id="id_supplier" value="{{supplier.id}}">
<thead>
	<tr>
		<th class="bg-primary">S.No</th>
		<th class="bg-primary">Certification Description</th>
		<th class="bg-primary">Cert. Number</th>
		<th class="bg-primary">Category</th>
		<th class="bg-primary">Cert Date</th>
		<th class="bg-primary">Expiration Date</th>
		<th class="bg-primary" width="100">How many years have you had this certification?</th>
		<th class="bg-primary">Upload certification</th>
	</tr>
</thead>

<tbody id="cert_list">
	
	<input type="hidden" name="company" value="{{company_id}}">
	{% for cert in cert_names %}
	<tr style="border-bottom: 2px solid #DDD;" id="{{cert.id}}">
		<td>
			{{cert.id}}
			<input type="hidden" name="certificate_name" value="{{cert.id}}">
		</td>
		<td width="200">
			{{cert.cert_name}}
		</td>
		<td><input type="text" name="cert_number" class="form-control" value=""></td>
		<td><input type="text" name="category" class="form-control" value=""></td>
		<td>
			<input type="text" name="certification_date" class="form-control datetime" value="">
		</td>
		<td><input type="text" name="expire_date" class="form-control datetime" value=""></td>
		<td>
			<input type="text" name="certificate_duration" class="form-control" value="">
		</td>
		<td>
			<input type="file" name="upload_certificate_{{forloop.counter0}}" value="no">
			<span class="file_name"></span>
		</td>
	</tr>
	{% endfor %}
	<tr>
		<td colspan="8">
			<button class="btn btn-primary">Submit & Continue</button>
		</td>
	</tr>
	
</tbody>

	

</form>
</table>

templates/supplier/company_certification.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/comp_cert_form.html" %}	

{% endblock %}

{% block page_js %}
<script type="text/javascript">


pr.controller('CompCertController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company cert controller...");
        var sup_id = $("#id_supplier").val();
        var url = "/supplier/profile/company/certification/api/"+sup_id+"/"
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                console.log(data);
                $scope.certs = data;

                for(i=0; i<$scope.certs.length; i++) {
                	var cert_id = $scope.certs[i].id;
                	var cert = $("tr#"+cert_id);
                	cert.find("input[name=cert_number]").val($scope.certs[i].company_cert.cert_number);
                	cert.find("input[name=category]").val($scope.certs[i].company_cert.category);
                	cert.find("input[name=certification_date]").val($scope.certs[i].company_cert.certification_date);
                	cert.find("input[name=expire_date]").val($scope.certs[i].company_cert.expire_date);
                	cert.find("input[name=certificate_duration]").val($scope.certs[i].company_cert.certificate_duration);
                	cert.find("span[class=file_name]").text($scope.certs[i].company_cert.upload_certificate);
                	
                }
                
        }).error(function() {
            console.log("no company info")
        });
    }
    $scope.init();

}]);

</script>
{% endblock %}

templates/supplier/company_contacts.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/form/company_contact_form.html" %}	
{% endblock %}

{% block page_js %}
<script type="text/javascript">
$('#pre-selected-options').multiSelect({
    selectableHeader: "<div class='bg-danger'>Selectable Category</div>",
    selectionHeader: "<div class='bg-danger'>Selected Category</div>"
});


pr.controller('CompContactController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company Contact controller...");
        var sup_id = $("#id_supplier").val();
        var url = "/supplier/profile/company/contacts/api/"+sup_id+"/"
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                $scope.comp_contact = data;
                // $scope.capability = data.capability
                
        }).error(function() {
            console.log("no company info")
        });

        var ref_url = "/supplier/profile/company/references/api/"+sup_id+"/";
        $http({method: 'GET', url: ref_url}).
            success(function(rdata, status, headers, config) {
                console.log(rdata);
                $scope.comp_reference = rdata;
                // $scope.capability = data.capability
                
        });
    }
    $scope.init();

}]);

</script>
{% endblock %}

templates/supplier/company_products_services.html
{% extends "layout.html" %}

{% block container %}
<style type="text/css">
#search_modal {
    position: absolute;
    top: -150px;
    left: -100px;
    width: 800px;
    height: 500px;
    border: 2px solid #ccc;
    background-color: #DDD;
    z-index: 1002;
}

</style>
	{% include "steps.html" %}
	{% include "supplier/form/company_product_service_form.html" %}
{% endblock %}

{% block page_js %}
<script type="text/javascript">

pr.controller('CompProServiceController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company Product Service controller...");
        var sup_id = $("#id_supplier").val();
        var url = "/supplier/profile/company/products-services/api/"+sup_id+"/"
        
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                console.log(data);
                $scope.comp_pro_service = data;

        }).error(function() {
            console.log("no company info")
        });

        $scope.show_search_modal = false;
    }
    $scope.init();

    $scope.ShowSearchPage = function(code) {
        $scope.url = "/supplier/search/code/naics/"
        $scope.show_search_modal = true;
    }

    $scope.HideMe = function() {
        $scope.show_search_modal = false;
    }

}]);
pr.controller('CodeSearchController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company Product Service controller...");
        var code_type = $("#id_code_type").val();
        var url = "/supplier/product-service/code/"+code_type+"/search/"
        console.log(code_type);
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                console.log(data);
                $scope.codes = data.results;

        }).error(function() {
            console.log("no company info")
        });
    }
    $scope.init();

}]);



</script>
{% endblock %}

templates/supplier/company_revenue.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/form/company_revenue_form.html" %}	
{% endblock %}

{% block page_js %}
<script type="text/javascript">

pr.controller('CompRevController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company Revenue controller...");
        var sup_id = $("#id_supplier").val();
        var url = "/supplier/profile/company/revenue/api/"+sup_id+"/"
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                $scope.revenue = data;
                // console.log(data);
                // $("#id_last_year_annual_sale").val(data);

        

        });
    }
    $scope.init();

}]);

(function(){
    

    
})(jQuery)
</script>
{% endblock %}

templates/supplier/left-menu.html
<div class="list-group" ng-controller="LeftMenuController">
  <a  class="list-group-item" id='profile-list' href="/supplier/profile/">
    Profile
  </a>
  <div id="collapseOne" class="profile">
    <a href="/supplier/profile/info/" class="list-group-item">Supplier Information</a>
    <a href="/supplier/profile/company/info/" class="list-group-item">Company Information</a>
    <a href="/supplier/profile/company/revenue/" class="list-group-item">Company Revenue</a>
    <a href="/supplier/profile/company/contacts/" class="list-group-item">Company Contact Info</a>
    <a href="/supplier/profile/company/licenses/" class="list-group-item">Licenses & Certifications</a>
    <a href="/supplier/profile/company/products-services/" class="list-group-item">Product & Services</a>
    <a href="/supplier/profile/company/certification/" class="list-group-item" ng-click="ActiveMenu($event)">Certification</a>
  </div>
  <a href="/supplier/search-corporation/" class="list-group-item">Search Corporation</a>
  <a href="#" class="list-group-item">Membership</a>
  <a href="#" class="list-group-item">Advanced Search</a>
  <a href="#" class="list-group-item">Corporation Update</a>
  
  <a href="/supplier/notification/" class="list-group-item">Notifications</a>
  <a href="/supplier/submission-status/" class="list-group-item">Submission Status</a>
</div>

templates/supplier/search_code.html
{% extends "base.html" %}

{% block full_container %}

{% endblock %}
{% block page_js %}

<script type="text/javascript">
var pr = angular.module("pr", [], function ($interpolateProvider) {
        $interpolateProvider.startSymbol("{[{");
        $interpolateProvider.endSymbol("}]}");
});


</script>
{% endblock %}

templates/supplier/search_corporation.html
{% extends "layout.html" %}

{% block page_css %}
	<link href="/static/css/multiselect.css" media="screen" rel="stylesheet" type="text/css">
<style type="text/css">

select[multiple], select[size] {
	height: 150px;
}
td.hello {
	position: relative;
}

.display_buyers {
	position: absolute;
	width: 70%;
}
.display_buyers thead {
	background-color: #333;
	color: #FFF;
}
.display_buyers tbody tr:hover {
	background-color: #DDD;
}
</style>
{% endblock %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/form/search.html" %}	
{% endblock %}

{% block page_js %}
<script type="text/javascript" src="/static/js/jquery.multi-select.js"></script>

<script type="text/javascript">
$('#corp-select').multiSelect();

pr.controller('SearchPageController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Search Page controller...");
        $scope.show_buyers_list = false;
        $scope.no_buyers_found = false;

        $scope.is_this_step1 = false;
        $scope.is_this_step2 = false;
        $scope.is_this_step3 = true;
    }
    $scope.init();

    $scope.searchBuyer = function(q) {
    	console.log(q);
    	if(q.length > 1) {
            var url = "/supplier/search/buyer/?q=" + q;
            $http({method: 'GET', url: url}).
	            success(function(data, status, headers, config){
	            	console.log(data.results.length);
	            	if (data.results.length > 0) {
	            		$scope.show_buyers_list = true;
	            		$scope.buyers = data;
	            		$scope.no_buyers_found = false;	
	            	} else {
	            		$scope.no_buyers_found = true;
	            	}
            		
	            
	        });
            
        } else {
            $scope.show_buyers_list = false;
        }
    }

    $scope.selectBuyer = function (buyer) {
    	$scope.show_buyers_list = false;
    	console.log(buyer);
    }

}]);

</script>
{% endblock %}

templates/supplier/searched_buyers.html
<div class="table-responsive">
  <div class="alert alert-info tb-header">List of Corporations (as per above selected criteria)</div>


	<form name="searched_form" id='searched_buyers'>{% csrf_token %}
  <table class="table table-striped table-hover  table-bordered">
  	<thead>
  		<tr>
  			<th width=7%><div align='center'>Sr.#<div></th>
  			<th width=45%>Corporation Name</th>
  			<th width=38%>Login URL</th>
  			<th width=10%><div align='center'>Select</div></th>
  		</tr>  		
  	</thead>
  	<tbody>
      {% if buyers %}
    		{% for buyer in buyers %}
    			<tr>
    				<td><div align='center'> {{ forloop.counter }} </div> </td>
    				<td> {{ buyer.company_name }} </td>
    				<td> {{ buyer.login_url }} </td>
    				<td>
              <div align='center'> 
                <input type='checkbox' name='buyers' value="{{ buyer.pk }}">
              </div>
            </td>
    			</tr>
    		{% endfor %}
      {% else %}
        <tr>
            <td colspan=4 class="danger" width=100%><div align='center'> No buyers found for your search </div> </td>
        </tr>
      {% endif %}
  	</tbody>
		<tfoot>
			<tr>
				<td colspan=4>
					<button type="submit" id='save' class="btn btn-primary pull-right">Save Selected Corporations</button>
				</td>
			</tr>
		</tfoot>    
  </table>
	</form>

</div>
  {% if no_buyer_found %}
    <div class="alert alert-danger tb-header">
      Following buyers name you manually added are not availale in our system
    </div>
    <table class="table table-striped table-hover  table-bordered">
      <tr>
        <th width=10%><div align='center'>Sr.#<div></th>
        <th> Buyers name</th>
      </tr>
    {% for byer in no_buyer_found %}
      <tr >
        <td class="danger" width=10%><div align='center'> {{ forloop.counter }} </div> </td>
        <td class="danger">{{ byer }} </td>
        
      </tr>
    {% endfor %}
    </table>

  {% else %}

  {% endif %}

<script type="text/javascript">
(function(){

  $("button#save").on('click', function(event) {
    // alert('hello');
    
    selectedbuyers = $("form#searched_buyers").serialize();
    console.log(selectedbuyers);
    
    $.ajax({
        type: "POST",
        url: "/supplier/save_buyers/",
        data: {
          'selectedbuyers': selectedbuyers,
          
        },

        success: function(data) {
          
          if(data=='No') {

            alert('You have not selected any buyers');

          } else if(data == 'NODELETE') {

            alert('You have this buyers already!');

          } else {

            $("#selectedbuyers tbody").html(data);
            $("#buyers").hide();
            $("#selectedbuyers .no-buyers-row").hide();

          }         
          
        },
        error: function(result) {
          alert('Error')
        }
    });
    
    event.preventDefault();
  });

})(jQuery)
</script>